version: '3.7'
services:
  spark-master:
    image: vovkman/spark:2.4.5
    networks:
      - spark-network
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      SPARK_LOCAL_IP: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    volumes:
      - .:/app
    command: ./start-master.sh
  spark-worker:
    image: vovkman/spark:2.4.5
    depends_on:
      - spark-master
    networks:
      - spark-network
    ports:
      - 8080
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 8080
    command: ./start-worker.sh

networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
